"""The JSON bodies actually sent to providers, kept in each agent's home.

The small index contains metadata only. Each body is a separate private file,
read in bounded chunks through the executor so a large prompt stays complete
without exceeding the socket's response budget.
"""

import base64
import json
import os
import re
import time
import uuid

from backend.core import paths
from backend.core import run_journal

cIndexFileName = "api-calls.jsonl"
cMaxCalls = 100
cMaxIndexBytes = 2 * 1024 * 1024
cChunkBytes = 256 * 1024
cCallIdPattern = re.compile(r"^[0-9]{20}-[a-f0-9]{32}$")


def fValidateCallId(pCallId):
  """Accept only an identifier generated by this recorder."""
  if not isinstance(pCallId, str) or not cCallIdPattern.fullmatch(pCallId):
    raise ValueError("Invalid API call id")
  return pCallId


def fGetIndexPath(pAgentId):
  return os.path.join(paths.fGetAgentHome(pAgentId), cIndexFileName)


def fGetBodyPath(pAgentId, pCallId):
  return os.path.join(paths.fGetAgentHome(pAgentId),
                      "api-call-%s.json" % (fValidateCallId(pCallId),))


def fReadCalls(pAgentId):
  """Return retained request metadata, newest first; no request bodies."""
  try:
    vText, _vTruncated = paths.fReadAgentOwnedFile(
      pAgentId, fGetIndexPath(pAgentId), cMaxIndexBytes, pKeepEnd=True)
  except FileNotFoundError:
    return []
  lCalls = []
  for vLine in vText.splitlines():
    try:
      dCall = json.loads(vLine)
      if not isinstance(dCall, dict):
        continue
      fValidateCallId(dCall.get("id"))
      lCalls.append(dCall)
    except (ValueError, TypeError):
      continue
  return list(reversed(lCalls[-cMaxCalls:]))


def fRecordCall(pAgentId, pRunId, pProvider, pModel, pStep, pMethod, pUrl, pBody):
  """Record a prepared JSON request before sending it, without headers."""
  vBody = pBody.encode("utf-8") if isinstance(pBody, str) else bytes(pBody)
  vCallId = "%020d-%s" % (time.time_ns(), uuid.uuid4().hex)
  vBodyPath = fGetBodyPath(pAgentId, vCallId)
  try:
    vDescriptor = os.open(vBodyPath, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(vDescriptor, "wb") as vFile:
      vFile.write(vBody)
    dCall = {
      "id": vCallId,
      "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
      "run_id": pRunId,
      "provider": pProvider,
      "model": pModel,
      "step": pStep,
      "method": pMethod,
      "url": pUrl,
      "bytes": len(vBody),
    }
    with run_journal.fOpenForAppend(fGetIndexPath(pAgentId)) as vFile:
      vFile.write(json.dumps(dCall, ensure_ascii=False) + "\n")
    fTrimCalls(pAgentId)
  except (OSError, ValueError):
    # Recording must never prevent an otherwise valid model request.
    return False
  return True


def fReadBodyChunk(pAgentId, pCallId, pOffset=0):
  """Read a complete request in small pieces, never following an agent's link."""
  if isinstance(pOffset, bool) or not isinstance(pOffset, int) or pOffset < 0:
    raise ValueError("offset must be a non-negative integer")
  vDescriptor, vSize = paths.fOpenAgentOwnedFile(
    pAgentId, fGetBodyPath(pAgentId, pCallId))
  try:
    if pOffset > vSize:
      raise ValueError("offset is past the end of the request")
    vData = os.pread(vDescriptor, cChunkBytes, pOffset)
  finally:
    os.close(vDescriptor)
  return {"data": base64.b64encode(vData).decode("ascii"),
          "next_offset": pOffset + len(vData), "size": vSize,
          "done": pOffset + len(vData) >= vSize}


def fTrimCalls(pAgentId):
  """Keep the newest complete requests, deleting only recorder-owned filenames."""
  lCalls = fReadCalls(pAgentId)
  sKept = {dCall["id"] for dCall in lCalls}
  vIndexPath = fGetIndexPath(pAgentId)
  vTemporaryPath = vIndexPath + ".tmp"
  try:
    with open(vTemporaryPath, "w", encoding="utf-8") as vFile:
      for dCall in reversed(lCalls):
        vFile.write(json.dumps(dCall, ensure_ascii=False) + "\n")
    os.chmod(vTemporaryPath, 0o600)
    os.replace(vTemporaryPath, vIndexPath)
    for vName in os.listdir(paths.fGetAgentHome(pAgentId)):
      if not vName.startswith("api-call-") or not vName.endswith(".json"):
        continue
      vCallId = vName[len("api-call-"):-len(".json")]
      if cCallIdPattern.fullmatch(vCallId) and vCallId not in sKept:
        os.unlink(fGetBodyPath(pAgentId, vCallId))
  finally:
    try:
      os.unlink(vTemporaryPath)
    except FileNotFoundError:
      pass
