"""Single-user authentication.

There is one account: the email address given at install time and a password
generated by the installer. That is the whole user model, because the
application is meant for one person on a LAN.

Being LAN-only changes what the threats are, not whether there are any. The
password is still hashed with argon2id and login attempts are still rate
limited, because "nobody outside can reach it" describes the network today, not
the laptop that joins the wifi tomorrow.
"""

import functools
import time

from argon2 import PasswordHasher
from argon2.exceptions import VerifyMismatchError, VerificationError, InvalidHashError
from flask import g, jsonify, redirect, request, session, url_for

from backend.core import db

# Session key holding the logged-in email address.
cSessionUserKey = "boa_user"

# Session key holding the epoch the session was granted under. A session whose
# number no longer matches the stored one is no longer a session.
cSessionEpochKey = "boa_epoch"

# Rate limiting. Ten tries in fifteen minutes from one address is far more than
# a person needs and far less than a script wants.
cMaxAttempts = 10
cAttemptWindowMinutes = 15

# How long a session stays valid without activity.
cSessionLifetimeHours = 12


def fGetPasswordHasher():
  """Return the argon2 hasher, configured as the installer configured it."""
  return PasswordHasher(time_cost=3, memory_cost=65536, parallelism=4)


def fGetAdministrator():
  """Return the single account row, or None when the install is incomplete."""
  vConnection = db.fOpenAppDb()
  try:
    vRow = vConnection.execute(
      "SELECT id, email, password_hash, session_epoch FROM admin WHERE id = 1"
    ).fetchone()
  finally:
    vConnection.close()
  return dict(vRow) if vRow else None


def fReadSessionEpoch():
  """Return the number every valid session must carry, or 0.

  Read on every request rather than cached, for the same reason the privileged
  daemon re-reads an agent's permissions on every tool call: the whole point of
  this number is that changing it takes effect at once. A cache would mean the
  session somebody just revoked keeps working until it expires, which is the
  behaviour this exists to remove.
  """
  dAdministrator = fGetAdministrator()
  if dAdministrator is None:
    return 0
  try:
    return int(dAdministrator.get("session_epoch") or 0)
  except (TypeError, ValueError):
    return 0


# There is deliberately no fBumpSessionEpoch().
#
# One was written and then removed: fChangePassword raises the epoch in the
# SAME UPDATE that writes the hash, so there is no moment in which the
# password is new and the old sessions are still valid - which is exactly the
# moment somebody holding a stolen session would need. A separate "invalidate
# every session" function is a second way to do it that does not have that
# property, sitting next to the one that does.


def fCountRecentFailures(pRemoteAddress):
  """Return how many failed attempts came from one address recently."""
  vConnection = db.fOpenAppDb()
  try:
    vRow = vConnection.execute(
      "SELECT COUNT(*) AS total FROM login_attempts "
      "WHERE remote_addr = ? AND succeeded = 0 "
      "AND attempted_at > datetime('now', ?)",
      (str(pRemoteAddress), "-%d minutes" % (cAttemptWindowMinutes,)),
    ).fetchone()
  finally:
    vConnection.close()
  return vRow["total"] if vRow else 0


def fRecordAttempt(pRemoteAddress, pSucceeded):
  """Record one login attempt."""
  vConnection = db.fOpenAppDb()
  try:
    vConnection.execute(
      "INSERT INTO login_attempts (remote_addr, succeeded) VALUES (?, ?)",
      (str(pRemoteAddress), 1 if pSucceeded else 0),
    )
    # Old attempts are pruned here rather than on a timer: the table only grows
    # when someone is logging in, so that is when it should be trimmed.
    vConnection.execute(
      "DELETE FROM login_attempts WHERE attempted_at < datetime('now', '-7 days')"
    )
    vConnection.commit()
  finally:
    vConnection.close()


def fVerifyCredentials(pEmail, pPassword):
  """Return True when the email and password match the single account."""
  dAdministrator = fGetAdministrator()
  if dAdministrator is None:
    return False

  vEmail = str(pEmail or "").strip().lower()
  if vEmail != str(dAdministrator["email"]).strip().lower():
    # The password is verified anyway, so that a wrong address and a wrong
    # password take the same amount of time to reject.
    try:
      fGetPasswordHasher().verify(dAdministrator["password_hash"], "not-the-password")
    except (VerifyMismatchError, VerificationError, InvalidHashError):
      pass
    return False

  try:
    fGetPasswordHasher().verify(dAdministrator["password_hash"], str(pPassword or ""))
  except (VerifyMismatchError, VerificationError, InvalidHashError):
    return False
  return True


def fLogIn(pEmail):
  """Start a session for the single account."""
  session.permanent = True
  session[cSessionUserKey] = str(pEmail).strip().lower()
  session[cSessionEpochKey] = fReadSessionEpoch()
  session["logged_in_at"] = int(time.time())


def fLogOut():
  """End the current session."""
  session.pop(cSessionUserKey, None)
  session.pop(cSessionEpochKey, None)
  session.pop("logged_in_at", None)


def fIsLoggedIn():
  """Return True when the request carries a session that is still valid.

  Holding a signed cookie is not the same thing as being allowed in. The
  cookie also has to carry the epoch it was granted under, and that epoch has
  to still be the current one - otherwise changing the password would leave
  every session opened before it working exactly as it did, which makes
  "change the password" useless as a way of throwing somebody out.

  A cookie with no epoch at all is refused: it was issued before this existed,
  and the safe reading of "I cannot tell when this was granted" is to ask for
  the password again.
  """
  if not session.get(cSessionUserKey):
    return False
  vCarried = session.get(cSessionEpochKey)
  if vCarried is None:
    return False
  try:
    return int(vCarried) == fReadSessionEpoch()
  except (TypeError, ValueError):
    return False


def fKeepThisSessionValid():
  """Re-stamp the current session after the epoch has been bumped.

  Changing your own password should not log you out of the browser you changed
  it in: what it should do is log out everyone else. Called by the endpoint
  right after the change, so the window in which this session is invalid never
  reaches a request.
  """
  if session.get(cSessionUserKey):
    session[cSessionEpochKey] = fReadSessionEpoch()


def fGetRemoteAddress():
  """Return the client address, trusting the local proxy's header.

  The local HAProxy sets X-Forwarded-For, and nothing else can reach these
  ports, so the last value in that header is the real client on the LAN.
  """
  vForwardedFor = request.headers.get("X-Forwarded-For", "")
  if vForwardedFor:
    return vForwardedFor.split(",")[-1].strip()
  return request.remote_addr or "unknown"


def fRequireLogin(pViewFunction):
  """Decorator: send anonymous callers to the login page, or refuse in JSON.

  An API call gets JSON and a browser gets a redirect, because a fetch() that
  receives the login page renders nothing useful and tells the user nothing.
  """
  @functools.wraps(pViewFunction)
  def fWrapper(*plArguments, **pdKeywords):
    if not fIsLoggedIn():
      if request.path.startswith("/api/"):
        return jsonify({"ok": False, "error": "Not logged in"}), 401
      return redirect(url_for("views.fLoginPage", next=request.path))
    g.vUserEmail = session.get(cSessionUserKey)
    return pViewFunction(*plArguments, **pdKeywords)
  return fWrapper


def fVerifyCurrentPassword(pPassword):
  """Return True when this is the password the account has right now.

  The email is not part of the question: there is one account, the caller is
  already logged into it, and what is being asked is whether the person at the
  keyboard is the one who set the password up.
  """
  dAdministrator = fGetAdministrator()
  if dAdministrator is None:
    return False
  try:
    fGetPasswordHasher().verify(dAdministrator["password_hash"],
                                str(pPassword or ""))
  except (VerifyMismatchError, VerificationError, InvalidHashError):
    return False
  return True


# The shortest password this accepts. Named rather than written into the
# message, because the interface writes that sentence now and needs the number
# to put in it.
cMinimumPasswordLength = 12


def fValidatePassword(pPassword):
  """Return the password, or raise saying what is wrong with it.

  Separate from fChangePassword so that a caller changing several things at
  once can find out whether all of them are acceptable before writing any of
  them. Validation that happens inside the write is validation that runs after
  the previous field has already changed.
  """
  vPassword = str(pPassword or "")
  if len(vPassword) < cMinimumPasswordLength:
    raise ValueError("The password must be at least %d characters long"
                     % (cMinimumPasswordLength,))
  return vPassword


def fValidateEmail(pEmail):
  """Return the normalised address, or raise. See fValidatePassword."""
  vEmail = str(pEmail or "").strip().lower()
  if "@" not in vEmail or "." not in vEmail.split("@")[-1]:
    raise ValueError("That is not a valid email address")
  return vEmail


def fChangePassword(pNewPassword, pCurrentPassword=None):
  """Replace the account password, having checked the current one.

  Knowing the old password is what makes this a change rather than a takeover.
  Without the check, anybody holding a session - a browser left open, or a
  session that outlived the credentials it was granted under - could set a new
  password without knowing the old one, and the owner would be locked out of
  their own installation by somebody who never knew a password at all.

  pCurrentPassword defaults to None rather than being required outright so
  that the installer's first write, which has no previous password to know,
  stays possible; every caller that is answering a person passes it.
  """
  if pCurrentPassword is not None and not fVerifyCurrentPassword(pCurrentPassword):
    raise ValueError("The current password is not correct")

  vPassword = fValidatePassword(pNewPassword)
  vHash = fGetPasswordHasher().hash(vPassword)
  vConnection = db.fOpenAppDb()
  try:
    # The epoch goes up in the same statement as the hash. Two statements
    # would leave a moment in which the password is new and the old sessions
    # are still valid, which is the moment somebody with a stolen session
    # would need.
    vConnection.execute(
      "UPDATE admin SET password_hash = ?, session_epoch = session_epoch + 1, "
      "updated_at = datetime('now') WHERE id = 1",
      (vHash,),
    )
    vConnection.commit()
  finally:
    vConnection.close()


def fChangeEmail(pNewEmail):
  """Replace the account email address."""
  vEmail = fValidateEmail(pNewEmail)
  vConnection = db.fOpenAppDb()
  try:
    vConnection.execute(
      "UPDATE admin SET email = ?, updated_at = datetime('now') WHERE id = 1",
      (vEmail,),
    )
    vConnection.commit()
  finally:
    vConnection.close()
