"""Single-user authentication.

There is one account: the email address given at install time and a password
generated by the installer. That is the whole user model, because the
application is meant for one person on a LAN.

Being LAN-only changes what the threats are, not whether there are any. The
password is still hashed with argon2id and login attempts are still rate
limited, because "nobody outside can reach it" describes the network today, not
the laptop that joins the wifi tomorrow.
"""

import functools
import time

from argon2 import PasswordHasher
from argon2.exceptions import VerifyMismatchError, VerificationError, InvalidHashError
from flask import g, jsonify, redirect, request, session, url_for

from backend.core import db

# Session key holding the logged-in email address.
cSessionUserKey = "boa_user"

# Rate limiting. Ten tries in fifteen minutes from one address is far more than
# a person needs and far less than a script wants.
cMaxAttempts = 10
cAttemptWindowMinutes = 15

# How long a session stays valid without activity.
cSessionLifetimeHours = 12


def fGetPasswordHasher():
  """Return the argon2 hasher, configured as the installer configured it."""
  return PasswordHasher(time_cost=3, memory_cost=65536, parallelism=4)


def fGetAdministrator():
  """Return the single account row, or None when the install is incomplete."""
  vConnection = db.fOpenAppDb()
  try:
    vRow = vConnection.execute(
      "SELECT id, email, password_hash FROM admin WHERE id = 1"
    ).fetchone()
  finally:
    vConnection.close()
  return dict(vRow) if vRow else None


def fCountRecentFailures(pRemoteAddress):
  """Return how many failed attempts came from one address recently."""
  vConnection = db.fOpenAppDb()
  try:
    vRow = vConnection.execute(
      "SELECT COUNT(*) AS total FROM login_attempts "
      "WHERE remote_addr = ? AND succeeded = 0 "
      "AND attempted_at > datetime('now', ?)",
      (str(pRemoteAddress), "-%d minutes" % (cAttemptWindowMinutes,)),
    ).fetchone()
  finally:
    vConnection.close()
  return vRow["total"] if vRow else 0


def fRecordAttempt(pRemoteAddress, pSucceeded):
  """Record one login attempt."""
  vConnection = db.fOpenAppDb()
  try:
    vConnection.execute(
      "INSERT INTO login_attempts (remote_addr, succeeded) VALUES (?, ?)",
      (str(pRemoteAddress), 1 if pSucceeded else 0),
    )
    # Old attempts are pruned here rather than on a timer: the table only grows
    # when someone is logging in, so that is when it should be trimmed.
    vConnection.execute(
      "DELETE FROM login_attempts WHERE attempted_at < datetime('now', '-7 days')"
    )
    vConnection.commit()
  finally:
    vConnection.close()


def fVerifyCredentials(pEmail, pPassword):
  """Return True when the email and password match the single account."""
  dAdministrator = fGetAdministrator()
  if dAdministrator is None:
    return False

  vEmail = str(pEmail or "").strip().lower()
  if vEmail != str(dAdministrator["email"]).strip().lower():
    # The password is verified anyway, so that a wrong address and a wrong
    # password take the same amount of time to reject.
    try:
      fGetPasswordHasher().verify(dAdministrator["password_hash"], "not-the-password")
    except (VerifyMismatchError, VerificationError, InvalidHashError):
      pass
    return False

  try:
    fGetPasswordHasher().verify(dAdministrator["password_hash"], str(pPassword or ""))
  except (VerifyMismatchError, VerificationError, InvalidHashError):
    return False
  return True


def fLogIn(pEmail):
  """Start a session for the single account."""
  session.permanent = True
  session[cSessionUserKey] = str(pEmail).strip().lower()
  session["logged_in_at"] = int(time.time())


def fLogOut():
  """End the current session."""
  session.pop(cSessionUserKey, None)
  session.pop("logged_in_at", None)


def fIsLoggedIn():
  """Return True when the request carries a valid session."""
  return bool(session.get(cSessionUserKey))


def fGetRemoteAddress():
  """Return the client address, trusting the local proxy's header.

  The local HAProxy sets X-Forwarded-For, and nothing else can reach these
  ports, so the last value in that header is the real client on the LAN.
  """
  vForwardedFor = request.headers.get("X-Forwarded-For", "")
  if vForwardedFor:
    return vForwardedFor.split(",")[-1].strip()
  return request.remote_addr or "unknown"


def fRequireLogin(pViewFunction):
  """Decorator: send anonymous callers to the login page, or refuse in JSON.

  An API call gets JSON and a browser gets a redirect, because a fetch() that
  receives the login page renders nothing useful and tells the user nothing.
  """
  @functools.wraps(pViewFunction)
  def fWrapper(*lArguments, **dKeywords):
    if not fIsLoggedIn():
      if request.path.startswith("/api/"):
        return jsonify({"ok": False, "error": "Not logged in"}), 401
      return redirect(url_for("views.fLoginPage", next=request.path))
    g.vUserEmail = session.get(cSessionUserKey)
    return pViewFunction(*lArguments, **dKeywords)
  return fWrapper


def fChangePassword(pNewPassword):
  """Replace the account password."""
  vPassword = str(pNewPassword or "")
  if len(vPassword) < 12:
    raise ValueError("The password must be at least 12 characters long")
  vHash = fGetPasswordHasher().hash(vPassword)
  vConnection = db.fOpenAppDb()
  try:
    vConnection.execute(
      "UPDATE admin SET password_hash = ?, updated_at = datetime('now') "
      "WHERE id = 1",
      (vHash,),
    )
    vConnection.commit()
  finally:
    vConnection.close()


def fChangeEmail(pNewEmail):
  """Replace the account email address."""
  vEmail = str(pNewEmail or "").strip().lower()
  if "@" not in vEmail or "." not in vEmail.split("@")[-1]:
    raise ValueError("That is not a valid email address")
  vConnection = db.fOpenAppDb()
  try:
    vConnection.execute(
      "UPDATE admin SET email = ?, updated_at = datetime('now') WHERE id = 1",
      (vEmail,),
    )
    vConnection.commit()
  finally:
    vConnection.close()
